/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 viper.gltf --transform
Author: zizian (https://sketchfab.com/zizian)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/supercar-viper-adrenaline-red-edition-fc211743356e43a1b757fb779e61d7aa
Title: Supercar Viper Adrenaline Red edition
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Viper(props) {
  const group = useRef()
  // debugger
  const { nodes, materials } = useGLTF('/viper-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh1_spoiler_p_0.geometry} material={materials.PaletteMaterial001} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh31_c1_0.geometry} material={materials.material} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh32_Color_K08_0.geometry} material={materials.Color_K08} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh34_window_o_0.geometry} material={materials.PaletteMaterial002} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh37_window0_0.geometry} material={materials.PaletteMaterial003} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh40_tail_light_0.geometry} material={materials.tail_light} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh45__Color_B01_1_0.geometry} material={materials.PaletteMaterial004} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh52_body_0.geometry} material={materials.PaletteMaterial005} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh54__9_0.geometry} material={materials.material_19} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh55__Translucent_Glass_Tinted_1_0.geometry} material={materials.Translucent_Glass_Tinted_1} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh55__1_0.geometry} material={materials.material_21} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh57__Color_K03_1_0.geometry} material={materials.Color_K03_1} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh71_Color_002_0.geometry} material={materials.PaletteMaterial006} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh88_ADVAN_Neova_AD08_2_0.geometry} material={materials.ADVAN_Neova_AD08_2} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh88_ADVAN_Neova_AD08_1_0.geometry} material={materials.ADVAN_Neova_AD08_1} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh183_Translucent_Glass_Tinted_0.geometry} material={materials.Translucent_Glass_Tinted} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh184_f_light_g1_0.geometry} material={materials.f_light_g1} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh186__3_0.geometry} material={materials.material_36} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh187__8_0.geometry} material={materials.material_39} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh197__7_0.geometry} material={materials.material_40} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh201_Translucent_Glass_Gray_0.geometry} material={materials.PaletteMaterial007} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh206__5_0.geometry} material={materials.material_47} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh206__6_0.geometry} material={materials.material_48} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh206__6_1_0.geometry} material={materials.material_49} rotation={[-1.578, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mesh206_c2_0.geometry} material={materials.material_52} rotation={[-1.578, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/viper-transformed.glb')
